// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FBServer.Migrations
{
    [DbContext(typeof(AppDbFBContext))]
    partial class AppDbFBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FBServer.Entity.db.Friendship", b =>
                {
                    b.Property<int>("FriendshipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("friendship_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FriendshipId"));

                    b.Property<int?>("Handshake")
                        .HasColumnType("integer")
                        .HasColumnName("handshake");

                    b.Property<int>("User1Id")
                        .HasColumnType("integer")
                        .HasColumnName("user1_id");

                    b.Property<int>("User2Id")
                        .HasColumnType("integer")
                        .HasColumnName("user2_id");

                    b.Property<int?>("ZeroUser")
                        .HasColumnType("integer")
                        .HasColumnName("zero_user");

                    b.HasKey("FriendshipId")
                        .HasName("friendships_pkey");

                    b.HasIndex("User2Id")
                        .HasDatabaseName("idx_friendships_user2_id");

                    b.HasIndex("User1Id", "User2Id")
                        .IsUnique()
                        .HasDatabaseName("friendships_user1_id_user2_id_key");

                    b.ToTable("friendships", "public", t =>
                        {
                            t.HasCheckConstraint("friendships_check", "user1_id < user2_id");
                        });
                });

            modelBuilder.Entity("FBServer.Entity.db.Request", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("result")
                        .HasColumnType("text")
                        .HasColumnName("result");

                    b.Property<int>("status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("id");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("FBServer.Entity.db.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("Another")
                        .HasColumnType("text")
                        .HasColumnName("another");

                    b.Property<string>("AnotherBasicInformation")
                        .HasColumnType("text")
                        .HasColumnName("another_basic_information");

                    b.Property<string>("AnotherCity")
                        .HasColumnType("text")
                        .HasColumnName("another_city");

                    b.Property<string>("AnotherContactInfo")
                        .HasColumnType("text")
                        .HasColumnName("another_contact_info");

                    b.Property<string>("AnotherWebSocialmedia")
                        .HasColumnType("text")
                        .HasColumnName("another_web_socialmedia");

                    b.Property<string>("Askfm")
                        .HasColumnType("text")
                        .HasColumnName("askfm");

                    b.Property<string>("Avatar")
                        .HasColumnType("text")
                        .HasColumnName("avatar");

                    b.Property<byte[]>("AvatarByte")
                        .HasColumnType("bytea")
                        .HasColumnName("avatar_byte");

                    b.Property<string>("Category")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<int?>("CheckLink")
                        .HasColumnType("integer")
                        .HasColumnName("check_link");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("DateOfCreation")
                        .HasColumnType("text")
                        .HasColumnName("date_of_creation");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Fio")
                        .HasColumnType("text")
                        .HasColumnName("fio");

                    b.Property<string>("Home")
                        .HasColumnType("text")
                        .HasColumnName("home");

                    b.Property<string>("Info")
                        .HasColumnType("text")
                        .HasColumnName("info");

                    b.Property<string>("Instagram")
                        .HasColumnType("text")
                        .HasColumnName("instagram");

                    b.Property<string>("Kakaotalk")
                        .HasColumnType("text")
                        .HasColumnName("kakaotalk");

                    b.Property<string>("Language")
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<string>("Line")
                        .HasColumnType("text")
                        .HasColumnName("line");

                    b.Property<string>("Link")
                        .HasColumnType("text")
                        .HasColumnName("link");

                    b.Property<string>("Linkedin")
                        .HasColumnType("text")
                        .HasColumnName("linkedin");

                    b.Property<string>("Male")
                        .HasColumnType("text")
                        .HasColumnName("male");

                    b.Property<string>("Mobile")
                        .HasColumnType("text")
                        .HasColumnName("mobile");

                    b.Property<string>("Ok")
                        .HasColumnType("text")
                        .HasColumnName("ok");

                    b.Property<string>("OpeningHours")
                        .HasColumnType("text")
                        .HasColumnName("opening_hours");

                    b.Property<string>("PageId")
                        .HasColumnType("text")
                        .HasColumnName("page_id");

                    b.Property<string>("Pinterest")
                        .HasColumnType("text")
                        .HasColumnName("pinterest");

                    b.Property<string>("PronounsInTheSystem")
                        .HasColumnType("text")
                        .HasColumnName("pronouns_in_the_system");

                    b.Property<string>("Reklama")
                        .HasColumnType("text")
                        .HasColumnName("reklama");

                    b.Property<string>("School")
                        .HasColumnType("text")
                        .HasColumnName("school");

                    b.Property<string>("School1")
                        .HasColumnType("text")
                        .HasColumnName("school1");

                    b.Property<string>("Site")
                        .HasColumnType("text")
                        .HasColumnName("site");

                    b.Property<string>("Skype")
                        .HasColumnType("text")
                        .HasColumnName("skype");

                    b.Property<string>("Snapchat")
                        .HasColumnType("text")
                        .HasColumnName("snapchat");

                    b.Property<string>("Soundcloud")
                        .HasColumnType("text")
                        .HasColumnName("soundcloud");

                    b.Property<string>("Spotify")
                        .HasColumnType("text")
                        .HasColumnName("spotify");

                    b.Property<string>("Subscribers")
                        .HasColumnType("text")
                        .HasColumnName("subscribers");

                    b.Property<string>("Threads")
                        .HasColumnType("text")
                        .HasColumnName("threads");

                    b.Property<string>("Tiktok")
                        .HasColumnType("text")
                        .HasColumnName("tiktok");

                    b.Property<string>("Twitch")
                        .HasColumnType("text")
                        .HasColumnName("twitch");

                    b.Property<string>("University")
                        .HasColumnType("text")
                        .HasColumnName("university");

                    b.Property<string>("University1")
                        .HasColumnType("text")
                        .HasColumnName("university1");

                    b.Property<string>("Vk")
                        .HasColumnType("text")
                        .HasColumnName("vk");

                    b.Property<string>("Wechat")
                        .HasColumnType("text")
                        .HasColumnName("wechat");

                    b.Property<string>("Whatsapp")
                        .HasColumnType("text")
                        .HasColumnName("whatsapp");

                    b.Property<string>("Work")
                        .HasColumnType("text")
                        .HasColumnName("work");

                    b.Property<string>("Work1")
                        .HasColumnType("text")
                        .HasColumnName("work1");

                    b.Property<string>("X")
                        .HasColumnType("text")
                        .HasColumnName("x");

                    b.Property<string>("Youtube")
                        .HasColumnType("text")
                        .HasColumnName("youtube");

                    b.HasKey("UserId")
                        .HasName("users_pk");

                    b.ToTable("users", "public");
                });

            modelBuilder.Entity("FBServer.Entity.db.Friendship", b =>
                {
                    b.HasOne("FBServer.Entity.db.User", "User1")
                        .WithMany()
                        .HasForeignKey("User1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("friendships_user1_id_fkey");

                    b.HasOne("FBServer.Entity.db.User", "User2")
                        .WithMany()
                        .HasForeignKey("User2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("friendships_user2_id_fkey");

                    b.Navigation("User1");

                    b.Navigation("User2");
                });
#pragma warning restore 612, 618
        }
    }
}
